/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import model.Donor;


/**
 *
 * @author zayna
 */
public class DeleteDonor extends javax.swing.JFrame {

    /**
     * Creates new form updateDetailsDonor
     */
    public DeleteDonor() {
        initComponents();
        fillCombo();
    }

    private void fillCombo() {
        ComboD_ID.removeAllItems();

        ArrayList<Integer> allD_ID = new Controller().getAllD_ID();

        for (int i = 0; i < allD_ID.size(); i++) {
            ComboD_ID.addItem(allD_ID.get(i) + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        SerachBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        D_Fname = new javax.swing.JTextField();
        D_Lname = new javax.swing.JTextField();
        D_address = new javax.swing.JTextField();
        D_number = new javax.swing.JTextField();
        D_gender = new javax.swing.JTextField();
        D_age = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        reset1 = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ComboD_ID = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Delete Donor DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 520, 44));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setText("Donor ID:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 27));

        SerachBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SerachBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/search1.png"))); // NOI18N
        SerachBut.setText("Search");
        SerachBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerachButActionPerformed(evt);
            }
        });
        getContentPane().add(SerachBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("First Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 27));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Last Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Address:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Number :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        D_Fname.setEditable(false);
        D_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_FnameActionPerformed(evt);
            }
        });
        getContentPane().add(D_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 161, 30));

        D_Lname.setEditable(false);
        D_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_LnameActionPerformed(evt);
            }
        });
        getContentPane().add(D_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 161, 30));

        D_address.setEditable(false);
        D_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_addressActionPerformed(evt);
            }
        });
        getContentPane().add(D_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 161, 30));

        D_number.setEditable(false);
        D_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_numberActionPerformed(evt);
            }
        });
        getContentPane().add(D_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 161, 30));

        D_gender.setEditable(false);
        D_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_genderActionPerformed(evt);
            }
        });
        getContentPane().add(D_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 161, 30));

        D_age.setEditable(false);
        D_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_ageActionPerformed(evt);
            }
        });
        getContentPane().add(D_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 161, 30));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/delete.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 120, 40));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 690, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 690, 10));

        reset1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Update details.png"))); // NOI18N
        reset1.setText("Reset");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 120, 40));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Exit application.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gender:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Age:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, -1));

        ComboD_ID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboD_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboD_IDActionPerformed(evt);
            }
        });
        getContentPane().add(ComboD_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 72, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SerachButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerachButActionPerformed

        int D_ID = Integer.parseInt(ComboD_ID.getSelectedItem().toString());
        Donor donor = new Controller().getDonorByD_ID(D_ID);

        if (donor != null) {
            D_Fname.setText(donor.getD_FName());
            D_Lname.setText(donor.getD_LName());
            D_age.setText(donor.getD_Age() + "");
            D_gender.setText(donor.getD_Gender());
            D_address.setText(donor.getD_Adress());
            D_number.setText(donor.getD_Number());
        }

    }//GEN-LAST:event_SerachButActionPerformed

    private void D_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_FnameActionPerformed

    private void D_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_LnameActionPerformed

    private void D_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_addressActionPerformed

    private void D_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_numberActionPerformed

    private void D_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_genderActionPerformed

    private void D_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_ageActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        int D_ID = Integer.parseInt(ComboD_ID.getSelectedItem().toString());
        new Controller().deleteDonorByD_ID(D_ID);

        D_Fname.setText("");
        D_Lname.setText("");
        D_age.setText("");
        D_gender.setText("");
        D_address.setText("");
        D_number.setText("");
        
        fillCombo();

    }//GEN-LAST:event_deleteActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        
        setVisible(false);
        new DeleteDonor().setVisible(true);
        
    }//GEN-LAST:event_reset1ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       
        setVisible(false);

    }//GEN-LAST:event_closeActionPerformed

    private void ComboD_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboD_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboD_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboD_ID;
    private javax.swing.JTextField D_Fname;
    private javax.swing.JTextField D_Lname;
    private javax.swing.JTextField D_address;
    private javax.swing.JTextField D_age;
    private javax.swing.JTextField D_gender;
    private javax.swing.JTextField D_number;
    private javax.swing.JButton SerachBut;
    private java.awt.Button button1;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton reset1;
    // End of variables declaration//GEN-END:variables
}
