/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author zayna
 */
public class LogInFrame extends javax.swing.JFrame {
    


    /**
     * Creates new form LogInFrame
     */
    public LogInFrame() {
        initComponents();
        setDefaultCloseOperation(LogInFrame.DISPOSE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbuttn = new javax.swing.JButton();
        closebuttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        check = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbuttn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbuttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/login.png"))); // NOI18N
        loginbuttn.setText("Login");
        loginbuttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbuttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 160, -1));

        closebuttn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closebuttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Exit application.png"))); // NOI18N
        closebuttn.setText("close");
        closebuttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttnActionPerformed(evt);
            }
        });
        getContentPane().add(closebuttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 161, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 90, 20));

        uname.setBackground(new java.awt.Color(255, 51, 0));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 220, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 790));

        pass.setBackground(new java.awt.Color(255, 51, 0));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 220, -1));

        check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        check.setText("Show Password");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 220, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/login background final.PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttnActionPerformed
       
        String username = uname.getText();
        String Pass = pass.getText();
        if (username.isEmpty() || Pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter Username and pass then Log in", "Missing log in field", JOptionPane.ERROR_MESSAGE);
        }else
              if(username.equals("bbms")&&Pass.equals("bbms")){//bbms:blood bank managmnent system
           HomeFrame admin=new HomeFrame();
           admin.setTitle("Home");
           admin.setVisible(true);
           uname.setText("");
           pass.setText("");
        }
        else
        JOptionPane.showMessageDialog(this, "Error, please enter username and password then log in again", "Wrong log in field", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_loginbuttnActionPerformed

    private void closebuttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttnActionPerformed
        
        int a=JOptionPane.showConfirmDialog(null, "Do you really want to close application","Select",JOptionPane.YES_NO_OPTION);
        if (a==0)
        System.exit(0);
        
    }//GEN-LAST:event_closebuttnActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
       
        if (check.isSelected())
            pass.setEchoChar((char)0);
        else 
            pass.setEchoChar('*');
                
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check;
    private javax.swing.JButton closebuttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loginbuttn;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

  

    
    
  
    }

