/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import model.Patient;

/**
 *
 * @author zayna
 */
public class updateDetailsPatient extends javax.swing.JFrame {

    /**
     * Creates new form updateDetailsDonor
     */
    public updateDetailsPatient() {
        initComponents();
        fillCombo();
    }

    private void fillCombo() {
        ComboP_ID.removeAllItems();

        ArrayList<Integer> allP_ID = new Controller().getAllP_ID();

        for (int i = 0; i < allP_ID.size(); i++) {
            ComboP_ID.addItem(allP_ID.get(i) + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        SerachBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        P_Fname = new javax.swing.JTextField();
        P_Lname = new javax.swing.JTextField();
        P_address = new javax.swing.JTextField();
        P_number = new javax.swing.JTextField();
        P_gender = new javax.swing.JTextField();
        P_age = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        reset1 = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ComboP_ID = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        P_BoodTypeRequest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        P_BloodQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        button1.setLabel("button1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/all page background image.png"))); // NOI18N
        jLabel10.setText(" ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/all page background image.png"))); // NOI18N
        jLabel7.setText("                    ");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE Patient DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 520, 44));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setText("Patient ID:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 27));

        SerachBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SerachBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/search1.png"))); // NOI18N
        SerachBut.setText("Search");
        SerachBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerachButActionPerformed(evt);
            }
        });
        getContentPane().add(SerachBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("First Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 27));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Last Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Address:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Number :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        P_Fname.setEditable(false);
        P_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_FnameActionPerformed(evt);
            }
        });
        getContentPane().add(P_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 161, 30));

        P_Lname.setEditable(false);
        P_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_LnameActionPerformed(evt);
            }
        });
        getContentPane().add(P_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 161, 30));

        P_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_addressActionPerformed(evt);
            }
        });
        getContentPane().add(P_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 161, 30));

        P_number.setEditable(false);
        P_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_numberActionPerformed(evt);
            }
        });
        getContentPane().add(P_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 161, 30));

        P_gender.setEditable(false);
        P_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_genderActionPerformed(evt);
            }
        });
        getContentPane().add(P_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 161, 30));

        P_age.setEditable(false);
        P_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_ageActionPerformed(evt);
            }
        });
        getContentPane().add(P_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 161, 30));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/save.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 120, 40));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 690, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 690, 10));

        reset1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Update details.png"))); // NOI18N
        reset1.setText("Reset");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 120, 40));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Exit application.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 120, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gender:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Age:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, -1));

        ComboP_ID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboP_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 72, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Blood Type Request:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        P_BoodTypeRequest.setEditable(false);
        getContentPane().add(P_BoodTypeRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Blood Quantity:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        P_BloodQuantity.setEditable(false);
        getContentPane().add(P_BloodQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SerachButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerachButActionPerformed

        int P_ID = Integer.parseInt(ComboP_ID.getSelectedItem().toString());
        Patient patient = new Controller().getPatientByP_ID(P_ID);

        if (patient != null) {
            P_Fname.setText(patient.getP_Fname());
            P_Lname.setText(patient.getP_Lname());
            P_age.setText(patient.getP_Age() + "");
            P_gender.setText(patient.getP_Gender());
            P_address.setText(patient.getP_Adress());
            P_number.setText(patient.getP_Number());
            P_BoodTypeRequest.setText(patient.getP_BloodType_request());
            P_BloodQuantity.setText(patient.getP_BloodQuantity() + "");
        }

    }//GEN-LAST:event_SerachButActionPerformed

    private void P_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_FnameActionPerformed

    private void P_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_LnameActionPerformed

    private void P_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_addressActionPerformed

    private void P_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_numberActionPerformed

    private void P_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_genderActionPerformed

    private void P_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_ageActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        int P_ID = Integer.parseInt(ComboP_ID.getSelectedItem().toString());
        String Address = P_address.getText();
        new Controller().UpdatePatientAdress(P_ID, Address);

        P_Fname.setText("");
        P_Lname.setText("");
        P_age.setText("");
        P_gender.setText("");
        P_address.setText("");
        P_number.setText("");
        P_BoodTypeRequest.setText("");
        P_BloodQuantity.setText("");
        
        fillCombo();

    }//GEN-LAST:event_updateActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
       
        setVisible(false);
        new updateDetailsPatient().setVisible(true);
        
    }//GEN-LAST:event_reset1ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       
        setVisible(false);

    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateDetailsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateDetailsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateDetailsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateDetailsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDetailsPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboP_ID;
    private javax.swing.JTextField P_BloodQuantity;
    private javax.swing.JTextField P_BoodTypeRequest;
    private javax.swing.JTextField P_Fname;
    private javax.swing.JTextField P_Lname;
    private javax.swing.JTextField P_address;
    private javax.swing.JTextField P_age;
    private javax.swing.JTextField P_gender;
    private javax.swing.JTextField P_number;
    private javax.swing.JButton SerachBut;
    private java.awt.Button button1;
    private javax.swing.JButton close;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton reset1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
