/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Azzam
 */
public class addNewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form addNewEmployee
     */
    public addNewEmployee() {
        initComponents();
        EID.setText(fill() + "");
    }
    
    private int fill() {
        ArrayList<Integer> ID = new Controller().getAllE_ID();
        int e = ID.get(ID.size()-1);
        e++;
        return e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BBID = new javax.swing.JTextField();
        FN = new javax.swing.JTextField();
        LN = new javax.swing.JTextField();
        EID = new javax.swing.JTextField();
        Adress = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Position = new javax.swing.JTextField();
        SaveBut = new javax.swing.JButton();
        CloseBut = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Add New Employee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 900, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Blood Bank ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Employee ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Position:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Number:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("First Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 277, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Adress:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Age:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        BBID.setEditable(false);
        BBID.setText("1");
        getContentPane().add(BBID, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 156, 235, 30));
        getContentPane().add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 272, 235, 30));
        getContentPane().add(LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 332, 235, 30));

        EID.setEditable(false);
        getContentPane().add(EID, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 220, 235, 30));
        getContentPane().add(Adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 235, 30));
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 395, 235, 30));
        getContentPane().add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 235, 30));
        getContentPane().add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 235, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Salary:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));
        getContentPane().add(Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 235, 30));

        SaveBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SaveBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/save.png"))); // NOI18N
        SaveBut.setText("Save");
        SaveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        CloseBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Exit application.png"))); // NOI18N
        CloseBut.setText("Close");
        CloseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 770, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButActionPerformed
        
        if (FN.getText().isEmpty() || LN.getText().isEmpty() || Age.getText().isEmpty() || Adress.getText().isEmpty() || Number.getText().isEmpty() || Position.getText().isEmpty()
                || Salary.getText().isEmpty())
         JOptionPane.showMessageDialog(this, "Enter required field(s) then continue", "Missing field(s)", JOptionPane.ERROR_MESSAGE);
        
        else{
        int BloodBID = Integer.parseInt(BBID.getText());
        int EmployeeID = Integer.parseInt(EID.getText());
        String Fname = FN.getText();
        String Lname = LN.getText();
        int age = Integer.parseInt(Age.getText());
        String adress = Adress.getText();
        String number = Number.getText();
        String position = Position.getText();
        int salary = Integer.parseInt(Salary.getText());
        
        new Controller().addEmployee(EmployeeID, Fname, Lname, adress, number, position, age, salary, BloodBID);
        
        FN.setText("");
        LN.setText("");
        Age.setText("");
        Adress.setText("");
        Number.setText("");
        Position.setText("");
        Salary.setText("");
        }
    }//GEN-LAST:event_SaveButActionPerformed

    private void CloseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButActionPerformed
      
        this.dispose();
        
    }//GEN-LAST:event_CloseButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adress;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField BBID;
    private javax.swing.JButton CloseBut;
    private javax.swing.JTextField EID;
    private javax.swing.JTextField FN;
    private javax.swing.JTextField LN;
    private javax.swing.JTextField Number;
    private javax.swing.JTextField Position;
    private javax.swing.JTextField Salary;
    private javax.swing.JButton SaveBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
