/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Azzam
 */
public class request extends javax.swing.JFrame {

    /**
     * Creates new form request
     */
    public request() {
        initComponents();
        P_ID.setText(fill() + "");

    }

    private int fill() {
        ArrayList<Integer> ID = new Controller().getAllP_ID();
        int p = ID.get(ID.size() - 1);
        p++;
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        ComboBloodType = new javax.swing.JComboBox<String>();
        id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        P_ID = new javax.swing.JTextField();
        P_Fname = new javax.swing.JTextField();
        P_Lname = new javax.swing.JTextField();
        P_bloodquantity = new javax.swing.JTextField();
        P_Number = new javax.swing.JTextField();
        P_Age = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        P_Address = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ComboGender = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        but1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        but2 = new javax.swing.JRadioButton();
        but3 = new javax.swing.JRadioButton();
        but4 = new javax.swing.JRadioButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText(" New REQUEST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 28, 276, 44));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 78, 763, 7));

        ComboBloodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(ComboBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 161, 30));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setText("Patient ID:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 120, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("First Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 120, 27));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Last Name:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 99, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 426, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Age:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 341, 68, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mobile Number :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText(" Address:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 511, 99, 30));

        P_ID.setEditable(false);
        P_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_IDActionPerformed(evt);
            }
        });
        getContentPane().add(P_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 125, 182, 30));

        P_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_FnameActionPerformed(evt);
            }
        });
        getContentPane().add(P_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 181, 182, 30));

        P_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_LnameActionPerformed(evt);
            }
        });
        getContentPane().add(P_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 253, 179, 30));

        P_bloodquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_bloodquantityActionPerformed(evt);
            }
        });
        getContentPane().add(P_bloodquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 161, 30));

        P_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_NumberActionPerformed(evt);
            }
        });
        getContentPane().add(P_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 161, 30));

        P_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_AgeActionPerformed(evt);
            }
        });
        getContentPane().add(P_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 336, 179, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Blood Type:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 105, 30));

        P_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_AddressActionPerformed(evt);
            }
        });
        getContentPane().add(P_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 513, 179, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Blood Quantity:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 127, 30));

        ComboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        getContentPane().add(ComboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 428, 179, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/print.png"))); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 581, 120, 40));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Update details.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 581, 120, 40));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/Exit application.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 581, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Hospital Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        buttonGroup1.add(but1);
        but1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        but1.setText("1");
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("El Hariri Hospital");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("AUB Hospital");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Nini Hospital");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Al Kheir Hospital");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        buttonGroup1.add(but2);
        but2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        but2.setText("2");
        getContentPane().add(but2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        buttonGroup1.add(but3);
        but3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        but3.setText("3");
        getContentPane().add(but3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        buttonGroup1.add(but4);
        but4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        but4.setText("4");
        getContentPane().add(but4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 565, 763, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 690, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_IDActionPerformed

    private void P_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_FnameActionPerformed

    private void P_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_LnameActionPerformed

    private void P_bloodquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_bloodquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_bloodquantityActionPerformed

    private void P_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_NumberActionPerformed

    private void P_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_AgeActionPerformed

    private void P_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_AddressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (P_Fname.getText().isEmpty() || P_Lname.getText().isEmpty() || P_Address.getText().isEmpty() || P_Number.getText().isEmpty() || P_Age.getText().isEmpty() || P_bloodquantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter required field(s) then continue", "Missing field(s)", JOptionPane.ERROR_MESSAGE);
        } else {
            int PatientID = Integer.parseInt(P_ID.getText());
            String Fname = P_Fname.getText();
            String Lname = P_Lname.getText();
            String address = P_Address.getText();
            String number = P_Number.getText();
            int age = Integer.parseInt(P_Age.getText());
            String gender = ComboGender.getSelectedItem().toString();
            int bloodquantity = Integer.parseInt(P_bloodquantity.getText());
            String bloodtype = ComboBloodType.getSelectedItem().toString();

            int HospitalID;
            if (but1.isSelected()) {
                HospitalID = 1;
            } else if (but2.isSelected()) {
                HospitalID = 2;
            } else if (but3.isSelected()) {
                HospitalID = 3;
            } else {
                HospitalID = 4;
            }

            new Controller().addPatient(PatientID, Fname, Lname, gender, address, age, bloodquantity, number, bloodtype);
            new Controller().addDelivers(PatientID, HospitalID);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        setVisible(false);
        new request().setVisible(true);

    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed

        setVisible(false);

    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new request().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBloodType;
    private javax.swing.JComboBox<String> ComboGender;
    private javax.swing.JTextField P_Address;
    private javax.swing.JTextField P_Age;
    private javax.swing.JTextField P_Fname;
    private javax.swing.JTextField P_ID;
    private javax.swing.JTextField P_Lname;
    private javax.swing.JTextField P_Number;
    private javax.swing.JTextField P_bloodquantity;
    private javax.swing.JRadioButton but1;
    private javax.swing.JRadioButton but2;
    private javax.swing.JRadioButton but3;
    private javax.swing.JRadioButton but4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
